openapi: 3.0.0
info:
  title: Gataama API
  description: Document to keep track of available api and test them
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /healthz:
    get:
      summary: Test server
      description: Confirms is server is up and running
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
components: